Feature/224 notifications
GreenCityProject/GreenCityMVP21_team1_August pull request #38
Opened 2024-09-02 14:19 UTC by ZenukD

As a registered user, I want to receive notifications so I can be informed about friend requests on the site.

**Scenario 1:
User receives a new notification
Acceptance Criteria:
GIVEN The user is logged in
WHEN The user receives a new notification
THEN The bell icon turns green
AND Displays the current number of unread notifications.
Mockup
Scenario 2:
User views the list of notifications
GIVEN The user has received new notifications
WHEN The user clicks on the bell icon
THEN A dropdown list appears with new messages related only to greencity.

BR1: Each notification in the dropdown list must contain the Section it relates to, the time the notification was received, and the text of the notification.

Scenario 3:
User navigates to the notifications section
GIVEN The user has opened the dropdown list of notifications
WHEN The user clicks on the "All notifications" button

2024-09-05 19:43 UTC, ChernenkoVitaliy requested changes
1. You have two identical enums even with the same names, NotificationSourceType. You should remove one of them. Or please explain why you need both.

2. You TOTALY have to review your changelog file 25-01-changelog.xml. You have 879 lines in it!!!! It is not supposed to change all those tables for the current task.

3. You should put the changelog file in the catalog with the name "logs". It is where all such files are stored.

2024-09-06 09:36 UTC, ChernenkoVitaliy approved these changes

2024-09-09 14:39 UTC, DmytroLysenko1 approved these changes

2024-09-20 05:11 UTC, NazarVavrushchak approved these changes

2024-09-25 12:18 UTC, merged